[package]
name = "carbon_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
#netcorehost = {version = "0.17.0", features = ["latest", "net8_0", "net7_0", "net6_0", "net5_0"]}
#lazy_static = "1.4.0"
bitflags = "2.5.0"
#widestring = "1.0.2"
anyhow = "1.0.82"
serde = "1.0.197"
serde_json = "1.0.115"
serde_derive = "1.0.197"
tabled = "0.15.0"
bytesize = "1.3.0"
#smol_str = "0.2.1"
#quinn = {version = "0.10.2"}