[package]
name = "CarbonNative"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true
lto = true
opt-level = 3

[dependencies]
#netcorehost = {version = "0.17.0", features = ["latest", "net8_0", "net7_0", "net6_0", "net5_0"]}
#lazy_static = "1.4.0"
bitflags = "2.5.0"
#widestring = "1.0.2"
#lz4_flex = "0.11.3"
#prost = "0.12.4"
#prost-derive = "0.12.4"
anyhow = "1.0.82"
serde = "1.0.199"
serde_json = "1.0.116"
serde_derive = "1.0.199"
#tabled = "0.15.0"
#bytesize = "1.3.0"
#smol_str = "0.2.1"
#quinn = {version = "0.10.2"}