[package]
name = "carbon_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netcorehost = {version = "0.15.1", features = ["latest", "net8_0", "net7_0", "net6_0", "net5_0"]}